// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobufs/AddFolder.proto

package me.camerongray.teamlocker.client.protobufs;

public final class AddFolder {
  private AddFolder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddFolderRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AddFolderRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Folder folder = 1;</code>
     */
    boolean hasFolder();
    /**
     * <code>.Folder folder = 1;</code>
     */
    me.camerongray.teamlocker.client.protobufs.Objects.Folder getFolder();
    /**
     * <code>.Folder folder = 1;</code>
     */
    me.camerongray.teamlocker.client.protobufs.Objects.FolderOrBuilder getFolderOrBuilder();
  }
  /**
   * Protobuf type {@code AddFolderRequest}
   */
  public  static final class AddFolderRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AddFolderRequest)
      AddFolderRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddFolderRequest.newBuilder() to construct.
    private AddFolderRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddFolderRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AddFolderRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              me.camerongray.teamlocker.client.protobufs.Objects.Folder.Builder subBuilder = null;
              if (folder_ != null) {
                subBuilder = folder_.toBuilder();
              }
              folder_ = input.readMessage(me.camerongray.teamlocker.client.protobufs.Objects.Folder.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(folder_);
                folder_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.camerongray.teamlocker.client.protobufs.AddFolder.internal_static_AddFolderRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.camerongray.teamlocker.client.protobufs.AddFolder.internal_static_AddFolderRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest.class, me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest.Builder.class);
    }

    public static final int FOLDER_FIELD_NUMBER = 1;
    private me.camerongray.teamlocker.client.protobufs.Objects.Folder folder_;
    /**
     * <code>.Folder folder = 1;</code>
     */
    public boolean hasFolder() {
      return folder_ != null;
    }
    /**
     * <code>.Folder folder = 1;</code>
     */
    public me.camerongray.teamlocker.client.protobufs.Objects.Folder getFolder() {
      return folder_ == null ? me.camerongray.teamlocker.client.protobufs.Objects.Folder.getDefaultInstance() : folder_;
    }
    /**
     * <code>.Folder folder = 1;</code>
     */
    public me.camerongray.teamlocker.client.protobufs.Objects.FolderOrBuilder getFolderOrBuilder() {
      return getFolder();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (folder_ != null) {
        output.writeMessage(1, getFolder());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (folder_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFolder());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest)) {
        return super.equals(obj);
      }
      me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest other = (me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest) obj;

      boolean result = true;
      result = result && (hasFolder() == other.hasFolder());
      if (hasFolder()) {
        result = result && getFolder()
            .equals(other.getFolder());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFolder()) {
        hash = (37 * hash) + FOLDER_FIELD_NUMBER;
        hash = (53 * hash) + getFolder().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddFolderRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AddFolderRequest)
        me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.camerongray.teamlocker.client.protobufs.AddFolder.internal_static_AddFolderRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.camerongray.teamlocker.client.protobufs.AddFolder.internal_static_AddFolderRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest.class, me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest.Builder.class);
      }

      // Construct using me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (folderBuilder_ == null) {
          folder_ = null;
        } else {
          folder_ = null;
          folderBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.camerongray.teamlocker.client.protobufs.AddFolder.internal_static_AddFolderRequest_descriptor;
      }

      public me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest getDefaultInstanceForType() {
        return me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest.getDefaultInstance();
      }

      public me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest build() {
        me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest buildPartial() {
        me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest result = new me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest(this);
        if (folderBuilder_ == null) {
          result.folder_ = folder_;
        } else {
          result.folder_ = folderBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest) {
          return mergeFrom((me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest other) {
        if (other == me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest.getDefaultInstance()) return this;
        if (other.hasFolder()) {
          mergeFolder(other.getFolder());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private me.camerongray.teamlocker.client.protobufs.Objects.Folder folder_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          me.camerongray.teamlocker.client.protobufs.Objects.Folder, me.camerongray.teamlocker.client.protobufs.Objects.Folder.Builder, me.camerongray.teamlocker.client.protobufs.Objects.FolderOrBuilder> folderBuilder_;
      /**
       * <code>.Folder folder = 1;</code>
       */
      public boolean hasFolder() {
        return folderBuilder_ != null || folder_ != null;
      }
      /**
       * <code>.Folder folder = 1;</code>
       */
      public me.camerongray.teamlocker.client.protobufs.Objects.Folder getFolder() {
        if (folderBuilder_ == null) {
          return folder_ == null ? me.camerongray.teamlocker.client.protobufs.Objects.Folder.getDefaultInstance() : folder_;
        } else {
          return folderBuilder_.getMessage();
        }
      }
      /**
       * <code>.Folder folder = 1;</code>
       */
      public Builder setFolder(me.camerongray.teamlocker.client.protobufs.Objects.Folder value) {
        if (folderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          folder_ = value;
          onChanged();
        } else {
          folderBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Folder folder = 1;</code>
       */
      public Builder setFolder(
          me.camerongray.teamlocker.client.protobufs.Objects.Folder.Builder builderForValue) {
        if (folderBuilder_ == null) {
          folder_ = builderForValue.build();
          onChanged();
        } else {
          folderBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Folder folder = 1;</code>
       */
      public Builder mergeFolder(me.camerongray.teamlocker.client.protobufs.Objects.Folder value) {
        if (folderBuilder_ == null) {
          if (folder_ != null) {
            folder_ =
              me.camerongray.teamlocker.client.protobufs.Objects.Folder.newBuilder(folder_).mergeFrom(value).buildPartial();
          } else {
            folder_ = value;
          }
          onChanged();
        } else {
          folderBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Folder folder = 1;</code>
       */
      public Builder clearFolder() {
        if (folderBuilder_ == null) {
          folder_ = null;
          onChanged();
        } else {
          folder_ = null;
          folderBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Folder folder = 1;</code>
       */
      public me.camerongray.teamlocker.client.protobufs.Objects.Folder.Builder getFolderBuilder() {
        
        onChanged();
        return getFolderFieldBuilder().getBuilder();
      }
      /**
       * <code>.Folder folder = 1;</code>
       */
      public me.camerongray.teamlocker.client.protobufs.Objects.FolderOrBuilder getFolderOrBuilder() {
        if (folderBuilder_ != null) {
          return folderBuilder_.getMessageOrBuilder();
        } else {
          return folder_ == null ?
              me.camerongray.teamlocker.client.protobufs.Objects.Folder.getDefaultInstance() : folder_;
        }
      }
      /**
       * <code>.Folder folder = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.camerongray.teamlocker.client.protobufs.Objects.Folder, me.camerongray.teamlocker.client.protobufs.Objects.Folder.Builder, me.camerongray.teamlocker.client.protobufs.Objects.FolderOrBuilder> 
          getFolderFieldBuilder() {
        if (folderBuilder_ == null) {
          folderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.camerongray.teamlocker.client.protobufs.Objects.Folder, me.camerongray.teamlocker.client.protobufs.Objects.Folder.Builder, me.camerongray.teamlocker.client.protobufs.Objects.FolderOrBuilder>(
                  getFolder(),
                  getParentForChildren(),
                  isClean());
          folder_ = null;
        }
        return folderBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AddFolderRequest)
    }

    // @@protoc_insertion_point(class_scope:AddFolderRequest)
    private static final me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest();
    }

    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddFolderRequest>
        PARSER = new com.google.protobuf.AbstractParser<AddFolderRequest>() {
      public AddFolderRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AddFolderRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddFolderRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddFolderRequest> getParserForType() {
      return PARSER;
    }

    public me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddFolderResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AddFolderResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.OperationResult result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>.OperationResult result = 1;</code>
     */
    me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult getResult();
    /**
     * <code>.OperationResult result = 1;</code>
     */
    me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResultOrBuilder getResultOrBuilder();

    /**
     * <code>.Folder folder = 2;</code>
     */
    boolean hasFolder();
    /**
     * <code>.Folder folder = 2;</code>
     */
    me.camerongray.teamlocker.client.protobufs.Objects.Folder getFolder();
    /**
     * <code>.Folder folder = 2;</code>
     */
    me.camerongray.teamlocker.client.protobufs.Objects.FolderOrBuilder getFolderOrBuilder();
  }
  /**
   * Protobuf type {@code AddFolderResponse}
   */
  public  static final class AddFolderResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AddFolderResponse)
      AddFolderResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddFolderResponse.newBuilder() to construct.
    private AddFolderResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddFolderResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AddFolderResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult.Builder subBuilder = null;
              if (result_ != null) {
                subBuilder = result_.toBuilder();
              }
              result_ = input.readMessage(me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(result_);
                result_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              me.camerongray.teamlocker.client.protobufs.Objects.Folder.Builder subBuilder = null;
              if (folder_ != null) {
                subBuilder = folder_.toBuilder();
              }
              folder_ = input.readMessage(me.camerongray.teamlocker.client.protobufs.Objects.Folder.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(folder_);
                folder_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.camerongray.teamlocker.client.protobufs.AddFolder.internal_static_AddFolderResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.camerongray.teamlocker.client.protobufs.AddFolder.internal_static_AddFolderResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse.class, me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult result_;
    /**
     * <code>.OperationResult result = 1;</code>
     */
    public boolean hasResult() {
      return result_ != null;
    }
    /**
     * <code>.OperationResult result = 1;</code>
     */
    public me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult getResult() {
      return result_ == null ? me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult.getDefaultInstance() : result_;
    }
    /**
     * <code>.OperationResult result = 1;</code>
     */
    public me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResultOrBuilder getResultOrBuilder() {
      return getResult();
    }

    public static final int FOLDER_FIELD_NUMBER = 2;
    private me.camerongray.teamlocker.client.protobufs.Objects.Folder folder_;
    /**
     * <code>.Folder folder = 2;</code>
     */
    public boolean hasFolder() {
      return folder_ != null;
    }
    /**
     * <code>.Folder folder = 2;</code>
     */
    public me.camerongray.teamlocker.client.protobufs.Objects.Folder getFolder() {
      return folder_ == null ? me.camerongray.teamlocker.client.protobufs.Objects.Folder.getDefaultInstance() : folder_;
    }
    /**
     * <code>.Folder folder = 2;</code>
     */
    public me.camerongray.teamlocker.client.protobufs.Objects.FolderOrBuilder getFolderOrBuilder() {
      return getFolder();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != null) {
        output.writeMessage(1, getResult());
      }
      if (folder_ != null) {
        output.writeMessage(2, getFolder());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResult());
      }
      if (folder_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFolder());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse)) {
        return super.equals(obj);
      }
      me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse other = (me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse) obj;

      boolean result = true;
      result = result && (hasResult() == other.hasResult());
      if (hasResult()) {
        result = result && getResult()
            .equals(other.getResult());
      }
      result = result && (hasFolder() == other.hasFolder());
      if (hasFolder()) {
        result = result && getFolder()
            .equals(other.getFolder());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResult()) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResult().hashCode();
      }
      if (hasFolder()) {
        hash = (37 * hash) + FOLDER_FIELD_NUMBER;
        hash = (53 * hash) + getFolder().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddFolderResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AddFolderResponse)
        me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.camerongray.teamlocker.client.protobufs.AddFolder.internal_static_AddFolderResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.camerongray.teamlocker.client.protobufs.AddFolder.internal_static_AddFolderResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse.class, me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse.Builder.class);
      }

      // Construct using me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (resultBuilder_ == null) {
          result_ = null;
        } else {
          result_ = null;
          resultBuilder_ = null;
        }
        if (folderBuilder_ == null) {
          folder_ = null;
        } else {
          folder_ = null;
          folderBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.camerongray.teamlocker.client.protobufs.AddFolder.internal_static_AddFolderResponse_descriptor;
      }

      public me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse getDefaultInstanceForType() {
        return me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse.getDefaultInstance();
      }

      public me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse build() {
        me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse buildPartial() {
        me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse result = new me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse(this);
        if (resultBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        if (folderBuilder_ == null) {
          result.folder_ = folder_;
        } else {
          result.folder_ = folderBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse) {
          return mergeFrom((me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse other) {
        if (other == me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse.getDefaultInstance()) return this;
        if (other.hasResult()) {
          mergeResult(other.getResult());
        }
        if (other.hasFolder()) {
          mergeFolder(other.getFolder());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult result_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult, me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult.Builder, me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResultOrBuilder> resultBuilder_;
      /**
       * <code>.OperationResult result = 1;</code>
       */
      public boolean hasResult() {
        return resultBuilder_ != null || result_ != null;
      }
      /**
       * <code>.OperationResult result = 1;</code>
       */
      public me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult getResult() {
        if (resultBuilder_ == null) {
          return result_ == null ? me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult.getDefaultInstance() : result_;
        } else {
          return resultBuilder_.getMessage();
        }
      }
      /**
       * <code>.OperationResult result = 1;</code>
       */
      public Builder setResult(me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          result_ = value;
          onChanged();
        } else {
          resultBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.OperationResult result = 1;</code>
       */
      public Builder setResult(
          me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult.Builder builderForValue) {
        if (resultBuilder_ == null) {
          result_ = builderForValue.build();
          onChanged();
        } else {
          resultBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.OperationResult result = 1;</code>
       */
      public Builder mergeResult(me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult value) {
        if (resultBuilder_ == null) {
          if (result_ != null) {
            result_ =
              me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult.newBuilder(result_).mergeFrom(value).buildPartial();
          } else {
            result_ = value;
          }
          onChanged();
        } else {
          resultBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.OperationResult result = 1;</code>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = null;
          onChanged();
        } else {
          result_ = null;
          resultBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.OperationResult result = 1;</code>
       */
      public me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult.Builder getResultBuilder() {
        
        onChanged();
        return getResultFieldBuilder().getBuilder();
      }
      /**
       * <code>.OperationResult result = 1;</code>
       */
      public me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResultOrBuilder getResultOrBuilder() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilder();
        } else {
          return result_ == null ?
              me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult.getDefaultInstance() : result_;
        }
      }
      /**
       * <code>.OperationResult result = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult, me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult.Builder, me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResultOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult, me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResult.Builder, me.camerongray.teamlocker.client.protobufs.MessageComponents.OperationResultOrBuilder>(
                  getResult(),
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }

      private me.camerongray.teamlocker.client.protobufs.Objects.Folder folder_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          me.camerongray.teamlocker.client.protobufs.Objects.Folder, me.camerongray.teamlocker.client.protobufs.Objects.Folder.Builder, me.camerongray.teamlocker.client.protobufs.Objects.FolderOrBuilder> folderBuilder_;
      /**
       * <code>.Folder folder = 2;</code>
       */
      public boolean hasFolder() {
        return folderBuilder_ != null || folder_ != null;
      }
      /**
       * <code>.Folder folder = 2;</code>
       */
      public me.camerongray.teamlocker.client.protobufs.Objects.Folder getFolder() {
        if (folderBuilder_ == null) {
          return folder_ == null ? me.camerongray.teamlocker.client.protobufs.Objects.Folder.getDefaultInstance() : folder_;
        } else {
          return folderBuilder_.getMessage();
        }
      }
      /**
       * <code>.Folder folder = 2;</code>
       */
      public Builder setFolder(me.camerongray.teamlocker.client.protobufs.Objects.Folder value) {
        if (folderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          folder_ = value;
          onChanged();
        } else {
          folderBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Folder folder = 2;</code>
       */
      public Builder setFolder(
          me.camerongray.teamlocker.client.protobufs.Objects.Folder.Builder builderForValue) {
        if (folderBuilder_ == null) {
          folder_ = builderForValue.build();
          onChanged();
        } else {
          folderBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Folder folder = 2;</code>
       */
      public Builder mergeFolder(me.camerongray.teamlocker.client.protobufs.Objects.Folder value) {
        if (folderBuilder_ == null) {
          if (folder_ != null) {
            folder_ =
              me.camerongray.teamlocker.client.protobufs.Objects.Folder.newBuilder(folder_).mergeFrom(value).buildPartial();
          } else {
            folder_ = value;
          }
          onChanged();
        } else {
          folderBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Folder folder = 2;</code>
       */
      public Builder clearFolder() {
        if (folderBuilder_ == null) {
          folder_ = null;
          onChanged();
        } else {
          folder_ = null;
          folderBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Folder folder = 2;</code>
       */
      public me.camerongray.teamlocker.client.protobufs.Objects.Folder.Builder getFolderBuilder() {
        
        onChanged();
        return getFolderFieldBuilder().getBuilder();
      }
      /**
       * <code>.Folder folder = 2;</code>
       */
      public me.camerongray.teamlocker.client.protobufs.Objects.FolderOrBuilder getFolderOrBuilder() {
        if (folderBuilder_ != null) {
          return folderBuilder_.getMessageOrBuilder();
        } else {
          return folder_ == null ?
              me.camerongray.teamlocker.client.protobufs.Objects.Folder.getDefaultInstance() : folder_;
        }
      }
      /**
       * <code>.Folder folder = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.camerongray.teamlocker.client.protobufs.Objects.Folder, me.camerongray.teamlocker.client.protobufs.Objects.Folder.Builder, me.camerongray.teamlocker.client.protobufs.Objects.FolderOrBuilder> 
          getFolderFieldBuilder() {
        if (folderBuilder_ == null) {
          folderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.camerongray.teamlocker.client.protobufs.Objects.Folder, me.camerongray.teamlocker.client.protobufs.Objects.Folder.Builder, me.camerongray.teamlocker.client.protobufs.Objects.FolderOrBuilder>(
                  getFolder(),
                  getParentForChildren(),
                  isClean());
          folder_ = null;
        }
        return folderBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AddFolderResponse)
    }

    // @@protoc_insertion_point(class_scope:AddFolderResponse)
    private static final me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse();
    }

    public static me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddFolderResponse>
        PARSER = new com.google.protobuf.AbstractParser<AddFolderResponse>() {
      public AddFolderResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AddFolderResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddFolderResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddFolderResponse> getParserForType() {
      return PARSER;
    }

    public me.camerongray.teamlocker.client.protobufs.AddFolder.AddFolderResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddFolderRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddFolderRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddFolderResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddFolderResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031protobufs/AddFolder.proto\032!protobufs/M" +
      "essageComponents.proto\032\027protobufs/Object" +
      "s.proto\"+\n\020AddFolderRequest\022\027\n\006folder\030\001 " +
      "\001(\0132\007.Folder\"N\n\021AddFolderResponse\022 \n\006res" +
      "ult\030\001 \001(\0132\020.OperationResult\022\027\n\006folder\030\002 " +
      "\001(\0132\007.FolderB,\n*me.camerongray.teamlocke" +
      "r.client.protobufsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          me.camerongray.teamlocker.client.protobufs.MessageComponents.getDescriptor(),
          me.camerongray.teamlocker.client.protobufs.Objects.getDescriptor(),
        }, assigner);
    internal_static_AddFolderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AddFolderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddFolderRequest_descriptor,
        new java.lang.String[] { "Folder", });
    internal_static_AddFolderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AddFolderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddFolderResponse_descriptor,
        new java.lang.String[] { "Result", "Folder", });
    me.camerongray.teamlocker.client.protobufs.MessageComponents.getDescriptor();
    me.camerongray.teamlocker.client.protobufs.Objects.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
