// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobufs/Objects.proto

package me.camerongray.teamlocker.client.protobufs;

public final class Objects {
  private Objects() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string username = 2;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>string username = 2;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>string full_name = 3;</code>
     */
    java.lang.String getFullName();
    /**
     * <code>string full_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getFullNameBytes();

    /**
     * <code>bytes auth_key = 4;</code>
     */
    com.google.protobuf.ByteString getAuthKey();

    /**
     * <code>bytes auth_key_hash = 5;</code>
     */
    com.google.protobuf.ByteString getAuthKeyHash();

    /**
     * <code>.LibsodiumItem encrypted_private_key = 6;</code>
     */
    boolean hasEncryptedPrivateKey();
    /**
     * <code>.LibsodiumItem encrypted_private_key = 6;</code>
     */
    me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem getEncryptedPrivateKey();
    /**
     * <code>.LibsodiumItem encrypted_private_key = 6;</code>
     */
    me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItemOrBuilder getEncryptedPrivateKeyOrBuilder();

    /**
     * <code>bytes public_key = 7;</code>
     */
    com.google.protobuf.ByteString getPublicKey();

    /**
     * <code>bytes kdf_salt = 8;</code>
     */
    com.google.protobuf.ByteString getKdfSalt();

    /**
     * <code>bool is_admin = 9;</code>
     */
    boolean getIsAdmin();
  }
  /**
   * Protobuf type {@code User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      id_ = 0;
      username_ = "";
      fullName_ = "";
      authKey_ = com.google.protobuf.ByteString.EMPTY;
      authKeyHash_ = com.google.protobuf.ByteString.EMPTY;
      publicKey_ = com.google.protobuf.ByteString.EMPTY;
      kdfSalt_ = com.google.protobuf.ByteString.EMPTY;
      isAdmin_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              username_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              fullName_ = s;
              break;
            }
            case 34: {

              authKey_ = input.readBytes();
              break;
            }
            case 42: {

              authKeyHash_ = input.readBytes();
              break;
            }
            case 50: {
              me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem.Builder subBuilder = null;
              if (encryptedPrivateKey_ != null) {
                subBuilder = encryptedPrivateKey_.toBuilder();
              }
              encryptedPrivateKey_ = input.readMessage(me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(encryptedPrivateKey_);
                encryptedPrivateKey_ = subBuilder.buildPartial();
              }

              break;
            }
            case 58: {

              publicKey_ = input.readBytes();
              break;
            }
            case 66: {

              kdfSalt_ = input.readBytes();
              break;
            }
            case 72: {

              isAdmin_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.camerongray.teamlocker.client.protobufs.Objects.internal_static_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.camerongray.teamlocker.client.protobufs.Objects.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.camerongray.teamlocker.client.protobufs.Objects.User.class, me.camerongray.teamlocker.client.protobufs.Objects.User.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object username_;
    /**
     * <code>string username = 2;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <code>string username = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FULL_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object fullName_;
    /**
     * <code>string full_name = 3;</code>
     */
    public java.lang.String getFullName() {
      java.lang.Object ref = fullName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fullName_ = s;
        return s;
      }
    }
    /**
     * <code>string full_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFullNameBytes() {
      java.lang.Object ref = fullName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fullName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTH_KEY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString authKey_;
    /**
     * <code>bytes auth_key = 4;</code>
     */
    public com.google.protobuf.ByteString getAuthKey() {
      return authKey_;
    }

    public static final int AUTH_KEY_HASH_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString authKeyHash_;
    /**
     * <code>bytes auth_key_hash = 5;</code>
     */
    public com.google.protobuf.ByteString getAuthKeyHash() {
      return authKeyHash_;
    }

    public static final int ENCRYPTED_PRIVATE_KEY_FIELD_NUMBER = 6;
    private me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem encryptedPrivateKey_;
    /**
     * <code>.LibsodiumItem encrypted_private_key = 6;</code>
     */
    public boolean hasEncryptedPrivateKey() {
      return encryptedPrivateKey_ != null;
    }
    /**
     * <code>.LibsodiumItem encrypted_private_key = 6;</code>
     */
    public me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem getEncryptedPrivateKey() {
      return encryptedPrivateKey_ == null ? me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem.getDefaultInstance() : encryptedPrivateKey_;
    }
    /**
     * <code>.LibsodiumItem encrypted_private_key = 6;</code>
     */
    public me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItemOrBuilder getEncryptedPrivateKeyOrBuilder() {
      return getEncryptedPrivateKey();
    }

    public static final int PUBLIC_KEY_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString publicKey_;
    /**
     * <code>bytes public_key = 7;</code>
     */
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }

    public static final int KDF_SALT_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString kdfSalt_;
    /**
     * <code>bytes kdf_salt = 8;</code>
     */
    public com.google.protobuf.ByteString getKdfSalt() {
      return kdfSalt_;
    }

    public static final int IS_ADMIN_FIELD_NUMBER = 9;
    private boolean isAdmin_;
    /**
     * <code>bool is_admin = 9;</code>
     */
    public boolean getIsAdmin() {
      return isAdmin_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getUsernameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, username_);
      }
      if (!getFullNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fullName_);
      }
      if (!authKey_.isEmpty()) {
        output.writeBytes(4, authKey_);
      }
      if (!authKeyHash_.isEmpty()) {
        output.writeBytes(5, authKeyHash_);
      }
      if (encryptedPrivateKey_ != null) {
        output.writeMessage(6, getEncryptedPrivateKey());
      }
      if (!publicKey_.isEmpty()) {
        output.writeBytes(7, publicKey_);
      }
      if (!kdfSalt_.isEmpty()) {
        output.writeBytes(8, kdfSalt_);
      }
      if (isAdmin_ != false) {
        output.writeBool(9, isAdmin_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getUsernameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, username_);
      }
      if (!getFullNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fullName_);
      }
      if (!authKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, authKey_);
      }
      if (!authKeyHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, authKeyHash_);
      }
      if (encryptedPrivateKey_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getEncryptedPrivateKey());
      }
      if (!publicKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, publicKey_);
      }
      if (!kdfSalt_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, kdfSalt_);
      }
      if (isAdmin_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, isAdmin_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.camerongray.teamlocker.client.protobufs.Objects.User)) {
        return super.equals(obj);
      }
      me.camerongray.teamlocker.client.protobufs.Objects.User other = (me.camerongray.teamlocker.client.protobufs.Objects.User) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getUsername()
          .equals(other.getUsername());
      result = result && getFullName()
          .equals(other.getFullName());
      result = result && getAuthKey()
          .equals(other.getAuthKey());
      result = result && getAuthKeyHash()
          .equals(other.getAuthKeyHash());
      result = result && (hasEncryptedPrivateKey() == other.hasEncryptedPrivateKey());
      if (hasEncryptedPrivateKey()) {
        result = result && getEncryptedPrivateKey()
            .equals(other.getEncryptedPrivateKey());
      }
      result = result && getPublicKey()
          .equals(other.getPublicKey());
      result = result && getKdfSalt()
          .equals(other.getKdfSalt());
      result = result && (getIsAdmin()
          == other.getIsAdmin());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + FULL_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFullName().hashCode();
      hash = (37 * hash) + AUTH_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getAuthKey().hashCode();
      hash = (37 * hash) + AUTH_KEY_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getAuthKeyHash().hashCode();
      if (hasEncryptedPrivateKey()) {
        hash = (37 * hash) + ENCRYPTED_PRIVATE_KEY_FIELD_NUMBER;
        hash = (53 * hash) + getEncryptedPrivateKey().hashCode();
      }
      hash = (37 * hash) + PUBLIC_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPublicKey().hashCode();
      hash = (37 * hash) + KDF_SALT_FIELD_NUMBER;
      hash = (53 * hash) + getKdfSalt().hashCode();
      hash = (37 * hash) + IS_ADMIN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsAdmin());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.camerongray.teamlocker.client.protobufs.Objects.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.camerongray.teamlocker.client.protobufs.Objects.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        me.camerongray.teamlocker.client.protobufs.Objects.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.camerongray.teamlocker.client.protobufs.Objects.internal_static_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.camerongray.teamlocker.client.protobufs.Objects.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.camerongray.teamlocker.client.protobufs.Objects.User.class, me.camerongray.teamlocker.client.protobufs.Objects.User.Builder.class);
      }

      // Construct using me.camerongray.teamlocker.client.protobufs.Objects.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        username_ = "";

        fullName_ = "";

        authKey_ = com.google.protobuf.ByteString.EMPTY;

        authKeyHash_ = com.google.protobuf.ByteString.EMPTY;

        if (encryptedPrivateKeyBuilder_ == null) {
          encryptedPrivateKey_ = null;
        } else {
          encryptedPrivateKey_ = null;
          encryptedPrivateKeyBuilder_ = null;
        }
        publicKey_ = com.google.protobuf.ByteString.EMPTY;

        kdfSalt_ = com.google.protobuf.ByteString.EMPTY;

        isAdmin_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.camerongray.teamlocker.client.protobufs.Objects.internal_static_User_descriptor;
      }

      public me.camerongray.teamlocker.client.protobufs.Objects.User getDefaultInstanceForType() {
        return me.camerongray.teamlocker.client.protobufs.Objects.User.getDefaultInstance();
      }

      public me.camerongray.teamlocker.client.protobufs.Objects.User build() {
        me.camerongray.teamlocker.client.protobufs.Objects.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.camerongray.teamlocker.client.protobufs.Objects.User buildPartial() {
        me.camerongray.teamlocker.client.protobufs.Objects.User result = new me.camerongray.teamlocker.client.protobufs.Objects.User(this);
        result.id_ = id_;
        result.username_ = username_;
        result.fullName_ = fullName_;
        result.authKey_ = authKey_;
        result.authKeyHash_ = authKeyHash_;
        if (encryptedPrivateKeyBuilder_ == null) {
          result.encryptedPrivateKey_ = encryptedPrivateKey_;
        } else {
          result.encryptedPrivateKey_ = encryptedPrivateKeyBuilder_.build();
        }
        result.publicKey_ = publicKey_;
        result.kdfSalt_ = kdfSalt_;
        result.isAdmin_ = isAdmin_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.camerongray.teamlocker.client.protobufs.Objects.User) {
          return mergeFrom((me.camerongray.teamlocker.client.protobufs.Objects.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.camerongray.teamlocker.client.protobufs.Objects.User other) {
        if (other == me.camerongray.teamlocker.client.protobufs.Objects.User.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          onChanged();
        }
        if (!other.getFullName().isEmpty()) {
          fullName_ = other.fullName_;
          onChanged();
        }
        if (other.getAuthKey() != com.google.protobuf.ByteString.EMPTY) {
          setAuthKey(other.getAuthKey());
        }
        if (other.getAuthKeyHash() != com.google.protobuf.ByteString.EMPTY) {
          setAuthKeyHash(other.getAuthKeyHash());
        }
        if (other.hasEncryptedPrivateKey()) {
          mergeEncryptedPrivateKey(other.getEncryptedPrivateKey());
        }
        if (other.getPublicKey() != com.google.protobuf.ByteString.EMPTY) {
          setPublicKey(other.getPublicKey());
        }
        if (other.getKdfSalt() != com.google.protobuf.ByteString.EMPTY) {
          setKdfSalt(other.getKdfSalt());
        }
        if (other.getIsAdmin() != false) {
          setIsAdmin(other.getIsAdmin());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.camerongray.teamlocker.client.protobufs.Objects.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.camerongray.teamlocker.client.protobufs.Objects.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>string username = 2;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string username = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string username = 2;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string username = 2;</code>
       */
      public Builder clearUsername() {
        
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>string username = 2;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        username_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fullName_ = "";
      /**
       * <code>string full_name = 3;</code>
       */
      public java.lang.String getFullName() {
        java.lang.Object ref = fullName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fullName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string full_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFullNameBytes() {
        java.lang.Object ref = fullName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fullName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string full_name = 3;</code>
       */
      public Builder setFullName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fullName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string full_name = 3;</code>
       */
      public Builder clearFullName() {
        
        fullName_ = getDefaultInstance().getFullName();
        onChanged();
        return this;
      }
      /**
       * <code>string full_name = 3;</code>
       */
      public Builder setFullNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fullName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString authKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes auth_key = 4;</code>
       */
      public com.google.protobuf.ByteString getAuthKey() {
        return authKey_;
      }
      /**
       * <code>bytes auth_key = 4;</code>
       */
      public Builder setAuthKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        authKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes auth_key = 4;</code>
       */
      public Builder clearAuthKey() {
        
        authKey_ = getDefaultInstance().getAuthKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString authKeyHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes auth_key_hash = 5;</code>
       */
      public com.google.protobuf.ByteString getAuthKeyHash() {
        return authKeyHash_;
      }
      /**
       * <code>bytes auth_key_hash = 5;</code>
       */
      public Builder setAuthKeyHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        authKeyHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes auth_key_hash = 5;</code>
       */
      public Builder clearAuthKeyHash() {
        
        authKeyHash_ = getDefaultInstance().getAuthKeyHash();
        onChanged();
        return this;
      }

      private me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem encryptedPrivateKey_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem, me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem.Builder, me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItemOrBuilder> encryptedPrivateKeyBuilder_;
      /**
       * <code>.LibsodiumItem encrypted_private_key = 6;</code>
       */
      public boolean hasEncryptedPrivateKey() {
        return encryptedPrivateKeyBuilder_ != null || encryptedPrivateKey_ != null;
      }
      /**
       * <code>.LibsodiumItem encrypted_private_key = 6;</code>
       */
      public me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem getEncryptedPrivateKey() {
        if (encryptedPrivateKeyBuilder_ == null) {
          return encryptedPrivateKey_ == null ? me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem.getDefaultInstance() : encryptedPrivateKey_;
        } else {
          return encryptedPrivateKeyBuilder_.getMessage();
        }
      }
      /**
       * <code>.LibsodiumItem encrypted_private_key = 6;</code>
       */
      public Builder setEncryptedPrivateKey(me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem value) {
        if (encryptedPrivateKeyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          encryptedPrivateKey_ = value;
          onChanged();
        } else {
          encryptedPrivateKeyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.LibsodiumItem encrypted_private_key = 6;</code>
       */
      public Builder setEncryptedPrivateKey(
          me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem.Builder builderForValue) {
        if (encryptedPrivateKeyBuilder_ == null) {
          encryptedPrivateKey_ = builderForValue.build();
          onChanged();
        } else {
          encryptedPrivateKeyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.LibsodiumItem encrypted_private_key = 6;</code>
       */
      public Builder mergeEncryptedPrivateKey(me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem value) {
        if (encryptedPrivateKeyBuilder_ == null) {
          if (encryptedPrivateKey_ != null) {
            encryptedPrivateKey_ =
              me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem.newBuilder(encryptedPrivateKey_).mergeFrom(value).buildPartial();
          } else {
            encryptedPrivateKey_ = value;
          }
          onChanged();
        } else {
          encryptedPrivateKeyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.LibsodiumItem encrypted_private_key = 6;</code>
       */
      public Builder clearEncryptedPrivateKey() {
        if (encryptedPrivateKeyBuilder_ == null) {
          encryptedPrivateKey_ = null;
          onChanged();
        } else {
          encryptedPrivateKey_ = null;
          encryptedPrivateKeyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.LibsodiumItem encrypted_private_key = 6;</code>
       */
      public me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem.Builder getEncryptedPrivateKeyBuilder() {
        
        onChanged();
        return getEncryptedPrivateKeyFieldBuilder().getBuilder();
      }
      /**
       * <code>.LibsodiumItem encrypted_private_key = 6;</code>
       */
      public me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItemOrBuilder getEncryptedPrivateKeyOrBuilder() {
        if (encryptedPrivateKeyBuilder_ != null) {
          return encryptedPrivateKeyBuilder_.getMessageOrBuilder();
        } else {
          return encryptedPrivateKey_ == null ?
              me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem.getDefaultInstance() : encryptedPrivateKey_;
        }
      }
      /**
       * <code>.LibsodiumItem encrypted_private_key = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem, me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem.Builder, me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItemOrBuilder> 
          getEncryptedPrivateKeyFieldBuilder() {
        if (encryptedPrivateKeyBuilder_ == null) {
          encryptedPrivateKeyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem, me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItem.Builder, me.camerongray.teamlocker.client.protobufs.Libsodium.LibsodiumItemOrBuilder>(
                  getEncryptedPrivateKey(),
                  getParentForChildren(),
                  isClean());
          encryptedPrivateKey_ = null;
        }
        return encryptedPrivateKeyBuilder_;
      }

      private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes public_key = 7;</code>
       */
      public com.google.protobuf.ByteString getPublicKey() {
        return publicKey_;
      }
      /**
       * <code>bytes public_key = 7;</code>
       */
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        publicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes public_key = 7;</code>
       */
      public Builder clearPublicKey() {
        
        publicKey_ = getDefaultInstance().getPublicKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString kdfSalt_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes kdf_salt = 8;</code>
       */
      public com.google.protobuf.ByteString getKdfSalt() {
        return kdfSalt_;
      }
      /**
       * <code>bytes kdf_salt = 8;</code>
       */
      public Builder setKdfSalt(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        kdfSalt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes kdf_salt = 8;</code>
       */
      public Builder clearKdfSalt() {
        
        kdfSalt_ = getDefaultInstance().getKdfSalt();
        onChanged();
        return this;
      }

      private boolean isAdmin_ ;
      /**
       * <code>bool is_admin = 9;</code>
       */
      public boolean getIsAdmin() {
        return isAdmin_;
      }
      /**
       * <code>bool is_admin = 9;</code>
       */
      public Builder setIsAdmin(boolean value) {
        
        isAdmin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_admin = 9;</code>
       */
      public Builder clearIsAdmin() {
        
        isAdmin_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final me.camerongray.teamlocker.client.protobufs.Objects.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.camerongray.teamlocker.client.protobufs.Objects.User();
    }

    public static me.camerongray.teamlocker.client.protobufs.Objects.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public me.camerongray.teamlocker.client.protobufs.Objects.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FolderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Folder)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code Folder}
   */
  public  static final class Folder extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Folder)
      FolderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Folder.newBuilder() to construct.
    private Folder(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Folder() {
      id_ = 0;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Folder(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.camerongray.teamlocker.client.protobufs.Objects.internal_static_Folder_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.camerongray.teamlocker.client.protobufs.Objects.internal_static_Folder_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.camerongray.teamlocker.client.protobufs.Objects.Folder.class, me.camerongray.teamlocker.client.protobufs.Objects.Folder.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.camerongray.teamlocker.client.protobufs.Objects.Folder)) {
        return super.equals(obj);
      }
      me.camerongray.teamlocker.client.protobufs.Objects.Folder other = (me.camerongray.teamlocker.client.protobufs.Objects.Folder) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.camerongray.teamlocker.client.protobufs.Objects.Folder parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.Folder parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.Folder parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.Folder parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.Folder parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.Folder parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.Folder parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.Folder parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.Folder parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.Folder parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.Folder parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.camerongray.teamlocker.client.protobufs.Objects.Folder parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.camerongray.teamlocker.client.protobufs.Objects.Folder prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Folder}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Folder)
        me.camerongray.teamlocker.client.protobufs.Objects.FolderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.camerongray.teamlocker.client.protobufs.Objects.internal_static_Folder_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.camerongray.teamlocker.client.protobufs.Objects.internal_static_Folder_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.camerongray.teamlocker.client.protobufs.Objects.Folder.class, me.camerongray.teamlocker.client.protobufs.Objects.Folder.Builder.class);
      }

      // Construct using me.camerongray.teamlocker.client.protobufs.Objects.Folder.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.camerongray.teamlocker.client.protobufs.Objects.internal_static_Folder_descriptor;
      }

      public me.camerongray.teamlocker.client.protobufs.Objects.Folder getDefaultInstanceForType() {
        return me.camerongray.teamlocker.client.protobufs.Objects.Folder.getDefaultInstance();
      }

      public me.camerongray.teamlocker.client.protobufs.Objects.Folder build() {
        me.camerongray.teamlocker.client.protobufs.Objects.Folder result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public me.camerongray.teamlocker.client.protobufs.Objects.Folder buildPartial() {
        me.camerongray.teamlocker.client.protobufs.Objects.Folder result = new me.camerongray.teamlocker.client.protobufs.Objects.Folder(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.camerongray.teamlocker.client.protobufs.Objects.Folder) {
          return mergeFrom((me.camerongray.teamlocker.client.protobufs.Objects.Folder)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.camerongray.teamlocker.client.protobufs.Objects.Folder other) {
        if (other == me.camerongray.teamlocker.client.protobufs.Objects.Folder.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.camerongray.teamlocker.client.protobufs.Objects.Folder parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.camerongray.teamlocker.client.protobufs.Objects.Folder) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Folder)
    }

    // @@protoc_insertion_point(class_scope:Folder)
    private static final me.camerongray.teamlocker.client.protobufs.Objects.Folder DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.camerongray.teamlocker.client.protobufs.Objects.Folder();
    }

    public static me.camerongray.teamlocker.client.protobufs.Objects.Folder getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Folder>
        PARSER = new com.google.protobuf.AbstractParser<Folder>() {
      public Folder parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Folder(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Folder> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Folder> getParserForType() {
      return PARSER;
    }

    public me.camerongray.teamlocker.client.protobufs.Objects.Folder getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Folder_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Folder_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027protobufs/Objects.proto\032\031protobufs/Lib" +
      "sodium.proto\"\307\001\n\004User\022\n\n\002id\030\001 \001(\005\022\020\n\010use" +
      "rname\030\002 \001(\t\022\021\n\tfull_name\030\003 \001(\t\022\020\n\010auth_k" +
      "ey\030\004 \001(\014\022\025\n\rauth_key_hash\030\005 \001(\014\022-\n\025encry" +
      "pted_private_key\030\006 \001(\0132\016.LibsodiumItem\022\022" +
      "\n\npublic_key\030\007 \001(\014\022\020\n\010kdf_salt\030\010 \001(\014\022\020\n\010" +
      "is_admin\030\t \001(\010\"\"\n\006Folder\022\n\n\002id\030\001 \001(\005\022\014\n\004" +
      "name\030\002 \001(\tB,\n*me.camerongray.teamlocker." +
      "client.protobufsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          me.camerongray.teamlocker.client.protobufs.Libsodium.getDescriptor(),
        }, assigner);
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Id", "Username", "FullName", "AuthKey", "AuthKeyHash", "EncryptedPrivateKey", "PublicKey", "KdfSalt", "IsAdmin", });
    internal_static_Folder_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Folder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Folder_descriptor,
        new java.lang.String[] { "Id", "Name", });
    me.camerongray.teamlocker.client.protobufs.Libsodium.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
